// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwb6HoFjWihTePpxAz5E-zTEartHI0abk',
    appId: '1:345022615835:web:efb06c7e02e362fe6983be',
    messagingSenderId: '345022615835',
    projectId: 'tourmetaverse',
    authDomain: 'tourmetaverse.firebaseapp.com',
    databaseURL: 'https://tourmetaverse-default-rtdb.firebaseio.com',
    storageBucket: 'tourmetaverse.appspot.com',
    measurementId: 'G-WGQHDVFQR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-k3qBpiyV6iTRBvC82-zra7hc5j2Y-r0',
    appId: '1:345022615835:android:3a1190f1fa3d93706983be',
    messagingSenderId: '345022615835',
    projectId: 'tourmetaverse',
    databaseURL: 'https://tourmetaverse-default-rtdb.firebaseio.com',
    storageBucket: 'tourmetaverse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOUVEJVt2Q4jKdcVLTmaGeq257APZfqS8',
    appId: '1:345022615835:ios:c0dd52ce48ec69eb6983be',
    messagingSenderId: '345022615835',
    projectId: 'tourmetaverse',
    databaseURL: 'https://tourmetaverse-default-rtdb.firebaseio.com',
    storageBucket: 'tourmetaverse.appspot.com',
    iosClientId:
        '345022615835-sj42blto08921mmrebdcuei2cfd4lo78.apps.googleusercontent.com',
    iosBundleId:
        'com.tourguide.metaverse.tourguidemetaversecab.tourGuideMetaversecab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOUVEJVt2Q4jKdcVLTmaGeq257APZfqS8',
    appId: '1:345022615835:ios:c0dd52ce48ec69eb6983be',
    messagingSenderId: '345022615835',
    projectId: 'tourmetaverse',
    databaseURL: 'https://tourmetaverse-default-rtdb.firebaseio.com',
    storageBucket: 'tourmetaverse.appspot.com',
    iosClientId:
        '345022615835-sj42blto08921mmrebdcuei2cfd4lo78.apps.googleusercontent.com',
    iosBundleId:
        'com.tourguide.metaverse.tourguidemetaversecab.tourGuideMetaversecab',
  );
}
